demo_camera:
  ros__parameters:
    # basic
    i_usb_speed: 'SUPER_PLUS'
    i_enable_lr: true
    i_enable_recording: false
    i_enable_logging: false
    i_enable_imu: false
    i_enable_rgb: true
    i_max_q_size: 4
    i_enable_depth: true
    # stereo
    i_mono_fps: 30.0
    i_mono_resolution: '480'
    i_align_depth: false
    i_lr_check: true
    i_lrc_threshold: 10
    i_depth_filter_size: 7
    i_stereo_depth_threshold: 240
    i_subpixel: true
    i_extended_disp: false
    i_rectify_edge_fill_color: -1
    i_enable_speckle_filter: true
    i_speckle_range: 60
    i_enable_temporal_filter: true
    i_enable_spatial_filter: true
    i_hole_filling_radius: 2
    i_spatial_filter_iterations: 1
    i_threshold_filter_min_range: 150
    i_threshold_filter_max_range: 4000
    i_decimation_factor: 1
    # rgb
    i_preview_size: 256
    i_rgb_resolution: "1080"
    i_rgb_fps: 30.0
    i_rgb_width: 640
    i_rgb_height: 480
    i_set_isp: false
    i_inverleaved: false
    i_keep_preview_aspect_ratio: true
    r_set_man_focus: true
    r_man_focus: 1
    r_set_man_exposure: false
    r_rgb_exposure: 1000
    r_rgb_iso: 100
    r_set_man_whitebalance: false
    r_whitebalance: 3300
