name: Docker Depthai Images Build Push

on:
  push:
    tags:
      - v*.*.*
  
jobs:
  docker-build-hw:
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        file: [docker/Dockerfile.deploy]                                                    

    steps:
    - name: Get current date
      id: date 
      run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d')"

    - name: Checkout
      uses: actions/checkout@v3    
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
     
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        file: ${{ matrix.file }}
        secrets: |
              "GIT_TOKEN=${{ secrets.GIT_TOKEN }}"
        build-args: |
              "BRANCH=${{ github.ref_name }}"
        push: true
        tags: novelte/depthai:${{ github.ref_name }}